source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'mikeLib_Example', :exclusive => true do
  pod "mikeLib", :path => "../"
end

target 'mikeLib_Tests', :exclusive => true do
  pod "mikeLib", :path => "../"

  
end
